
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Illuminate.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ContentTag
{

    public int ContentId { get; set; }

    public int TagId { get; set; }

    public string TaggedBy { get; set; }

    public string Description { get; set; }

}

}
