//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Illuminate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string Data { get; set; }
        public string Uri { get; set; }
        public string CreatorRef { get; set; }
        public string UpdaterRef { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
    }
}
