

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Illuminate.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class IlluminateEntities : DbContext
{
    public IlluminateEntities()
        : base("name=IlluminateEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Content> Contents { get; set; }

    public DbSet<Category> Categories { get; set; }

    public DbSet<ContentComment> ContentComments { get; set; }

    public DbSet<ContentFollower> ContentFollowers { get; set; }

    public DbSet<ContentLike> ContentLikes { get; set; }

    public DbSet<ContentTag> ContentTags { get; set; }

    public DbSet<Tag> Tags { get; set; }

    public DbSet<UserProfile> UserProfiles { get; set; }

}

}

